export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_POKEMON_ABILITIES = "REQUEST_POKEMON_ABILITIES";
export const GET_POKEMON_CHARACTERISTICS = "GET_POKEMON_CHARACTERISTICS";
export const GET_POKEMON_GENDERS = "GET_POKEMON_GENDERS";
export const GET_POKEMON_STATS = "GET_POKEMON_STATS";
export const GET_POKEMON_TYPES = "GET_POKEMON_TYPES";
export const IS_DATA_LOADING = "IS_DATA_LOADING";
