export enum ActionTypes {
    //setters
    SET_ALL_POKEMONS = "SET_ALL_POKEMONS",
    SET_POKEMON_DATA = "SET_POKEMON_DATA",
    SET_POKEMON_DATA_BY_TYPE = "SET_POKEMON_DATA_BY_TYPE",

    //getters
    GET_POKEMONS_INIT = "GET_POKEMONS_INIT",
    GET_POKEMONS_COMPLETE = "GET_POKEMONS_COMPLETE",
    GET_POKEMONS_FAIL = "GET_POKEMONS_FAIL",
    GET_POKEMON_ABILITIES = "REQUEST_POKEMON_ABILITIES",
    GET_POKEMON_CHARACTERISTICS = "GET_POKEMON_CHARACTERISTICS",
    GET_POKEMON_GENDERS = "GET_POKEMON_GENDERS",
    GET_POKEMON_STATS = "GET_POKEMON_STATS",
    GET_POKEMON_TYPES_INIT = "GET_POKEMON_TYPES_COMPLETE",
    GET_POKEMON_TYPES_COMPLETE = "GET_POKEMON_TYPES_COMPLETE",
    GET_POKEMON_TYPES_FAIL = "GET_POKEMON_TYPES_COMPLETE",

    //search
    SEARCH_POKEMON = "SEARCH_POKEMON",

    //init
    INIT_POKEMONS = "INIT_POKEMONS",
}
